In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [40]:
# define global variables
test_size = 0.3
random_state = 0

In [3]:
# Importing the dataset
# mostly using pandas

In [6]:
# Read the dataset
dataset = pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [35]:
# Create matrix X and Y as numpy arrays 
# if we dont use .values, it will remain a dataframe
# Assumption: Y is always the last column
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [36]:
# Work on missing data

In [37]:
# Replace the missing data with mean 
from sklearn.preprocessing import Imputer
# axis 0 to take the average of the entire column
# Other options are median and mode
imputer = Imputer(missing_values ='NaN', strategy ='mean', axis = 0)
imputer = imputer.fit(X[:, 1:3]) # Fit for Age and salary
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [38]:
# Work on categorical data

In [39]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# TODO: Create a function and move to common functions 
labelencoder_X = LabelEncoder()
# Change the column index based on where we have the categorical data
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)

# This is just one hot encoding.. not tackling the dummy variable trap yet
onehotencoder_X = OneHotEncoder(categorical_features = [0])
X = onehotencoder_X.fit_transform(X).toarray()
print(X)

labelencoder_Y = LabelEncoder()
# Change the column index based on where we have the categorical data
Y = labelencoder_Y.fit_transform(Y)
print(Y)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]
[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   4.40000000e+01
    7.20000000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   2.70000000e+01
    4.80000000e+04]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   3.00000000e+01
    5.40000000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   3.80000000e+01
    6.10000000e+04]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   4.00000000e+01
    6.37777778e+04]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   3.50000000e+01
    5.80000000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   3.87777778e+01
    5.20000000e+04]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   4.80000000e+01
    7.90000000e+04]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   5.00000000e+01
    8.

In [49]:
# Split into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = test_size, random_state = random_state)

print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   3.70000000e+01
    6.70000000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   2.70000000e+01
    4.80000000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   3.87777778e+01
    5.20000000e+04]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   4.80000000e+01
    7.90000000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   3.80000000e+01
    6.10000000e+04]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   4.40000000e+01
    7.20000000e+04]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   3.50000000e+01
    5.80000000e+04]]
[[  0.00000000e+00   1.00000000e+00   0.00000000e+00   3.00000000e+01
    5.40000000e+04]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   5.00000000e+01
    8.30000000e+04]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   4.00000000e+01
    6.37777778e+04]]
[1 1 0 1 0 0 1]
[0 0 1]


In [50]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
scaler_X = StandardScaler()
X_train = scaler_X.fit_transform(X_train)
# No reason to fit for test, because we want to use the same fit we used for training for the test as well
X_test = scaler_X.transform(X_test)

print(X_train)
print(X_test)

[[ 0.8660254   0.         -0.8660254  -0.2029809   0.44897083]
 [-1.15470054  0.          1.15470054 -1.82168936 -1.41706417]
 [-1.15470054  0.          1.15470054  0.08478949 -1.0242147 ]
 [ 0.8660254   0.         -0.8660254   1.5775984   1.62751925]
 [-1.15470054  0.          1.15470054 -0.04111006 -0.14030338]
 [ 0.8660254   0.         -0.8660254   0.93011502  0.94003267]
 [ 0.8660254   0.         -0.8660254  -0.52672259 -0.43494049]]
[[-1.15470054  1.         -0.8660254  -1.33607682 -0.82778996]
 [-1.15470054  1.         -0.8660254   1.90134009  2.02036872]
 [-1.15470054  1.         -0.8660254   0.28263164  0.13250875]]
